[package]
name = "level2-gasfee-query"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.4", features =  ["full"]  }
tokio = { version = "1", features = ["full"] }
eyre = "0.6"
url = "2"